fink_group_id: weizmann_k
fink_password: null
fink_servers: 134.158.74.95:24499
fink_topics:
- fink_rate_based_kn_candidates_ztf
- fink_kn_candidates_ztf
- fink_early_kn_candidates_ztf
- fink_sn_candidates_ztf
- fink_early_sn_candidates_ztf
fink_username: weizmann
skyportal_group: NMMA-SkyPortal
skyportal_token: 06b91ee9-92ab-4f3c-96a7-e725b8328fe7
skyportal_url: http://localhost:5000
testing: false
whitelisted: true
