fink_group_id: weizmann_k
fink_password: null
fink_servers: 134.158.74.95:24499
fink_topics:
- fink_rate_based_kn_candidates_ztf
- fink_kn_candidates_ztf
- fink_early_kn_candidates_ztf
- fink_sn_candidates_ztf
- fink_early_sn_candidates_ztf
fink_username: weizmann
skyportal_group: NMMA-SkyPortal
skyportal_token: bbff1882-ac7d-4539-9e76-f97b9dd387f6
skyportal_url: http://localhost:5000
testing: false
whitelisted: true
